config/routes.rb
Moviemarathonhelper::Application.routes.draw do
  
  resources :movies do
      resources :reviews
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :reviews
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'
  match '/search_movie', to: 'movies#movie_search'
  match '/logout', to: 'sessions#destroy'
  match '/help', to: 'static_pages#help'
  

end

app/controllers/movies_controller.rb
require "pp"
require "json"

class MoviesController < ApplicationController

	before_filter :find_movie, only: [:show, :destroy]
	skip_before_filter :require_login, only: [:movie_search]
	def new
		@movie = Movie.new
	end

	def movie_search
		@mv = Movie.new
		moviename = params[:movie].downcase
		# this is the url if a moviename is given
		url = URI.encode("http://www.omdbapi.com/?t=#{moviename}&plot=full")

		# this is the url if an imdb id is given, tried after the movie
		url_w_id = URI.encode("http://www.omdbapi.com/?i=#{moviename}&plot=full")
		@movie = JSON.parse HTTParty.get(url).response.body

		if @movie["Response"] == "True"
			extract_variables
		else
			@movie = JSON.parse HTTParty.get(url_w_id).response.body
			if @movie["Response"] == "True"
				extract_variables
			end
		end
	end

	def destroy
		if @movie.destroy 
			flash[:success] = "Movie deleted"
			redirect_to movies_path
		end
	end

	def show
		@review = @movie.reviews.find(:first, conditions: ["user_id = ?", current_user.id])
		@reviews = Review.find(:all, conditions: ["movie_id = ?", @movie.id])
	end

	def create
		@movie = Movie.new(params[:movie])
		if @movie.save
			redirect_to @movie
		else
			redirect_to user_path current_user
		end
		
	end

	def edit
		
	end

	def update
		
	end

	def index
		@movies = Movie.all
		@reviews = Review.all
	end

	def find_movie
		@movie = Movie.find(params[:id])
	end

	def extract_variables
		@actors = @movie["Actors"].split(/, */)
		@genres = @movie["Genre"].split(/, */)
		@directors = @movie["Director"].split(/, */)
		@writers = @movie["Writer"].split(/, */)
	end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for @mv do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<%= f.hidden_field :title, value: @movie["Title"] %>
	<%= f.hidden_field :writer, value: @movie["Writer"] %>
	<%= f.hidden_field :director, value: @movie["Director"] %>
	<%= f.hidden_field :actors, value: @movie["Actors"] %>
	<%= f.hidden_field :genre, value: @movie["Genre"] %>
	<%= f.hidden_field :imdbid, value: @movie["imdbID"] %>
	<%= f.hidden_field :imdbrating, value: @movie["imdbRating"] %>
	<%= f.hidden_field :plot, value: @movie["Plot"] %>
	<%= f.hidden_field :rated, value: @movie["Rated"] %>
	<%= f.hidden_field :released, value: @movie["Released"] %>
	<%= f.hidden_field :poster, value: @movie["Poster"] %>
	<%= f.hidden_field :imdbvotes, value: @movie["imdbVotes"] %>
	<%= f.hidden_field :year, value: @movie["Year"] %>
	<%= f.hidden_field :runtime, value: @movie["Runtime"] %>
	<%= f.submit "Add movie to database", class: "button centered" %>
<% end %>

app/views/movies/_movie.html.erb
<h2><%= link_to movie.title, movie %>
</h2>
<div>
	<ul class="small-block-grid-2">
		<li><%=link_to image_tag(movie.poster), movie %></li>
		<li><p><%= movie.plot[0..200]%>..</p></li>
		<li><div class="panel">
			<strong>Released:</strong>
		<p><%= movie.released %></p>

		<strong>Directors:</strong>
		<ul class="no-bullet">
		<li><%= movie.director %></li>
		</ul>

		<strong>Writers:</strong>
		<ul class="no-bullet">
		<li><%= movie.writer %></li>
		</ul>

		<strong>Actors:</strong>
		<ul class="no-bullet">
		<li><%= movie.actors %></li>

		
		</ul>
		<strong>Average rating by marathoners:</strong>
		<div>
			<% if not movie.avg_rating.nil? %>
				<%= movie.avg_rating %>
			<% else %>
				This movie has not been reviewed yet.
			<% end %>
		</div>
		</div>
		</li>
	</ul>
</div>

app/views/movies/_stats.html.erb
<strong>Released:</strong>
<p><%= @movie.released %></p>

<strong>Directors:</strong>
<ul class="no-bullet">
<li><%= @movie.director %></li>
</ul>

<strong>Writers:</strong>
<ul class="no-bullet">
<li><%= @movie.writer %></li>
</ul>

<strong>Actors:</strong>
<ul class="no-bullet">
<li><%= @movie.actors %></li>
</ul>

<strong>Genres:</strong>
<ul class="no-bullet">
<li><%= @movie.genre %></li>
</ul>
<strong>Runtime:</strong>
<p><%= @movie.runtime %></p>

<strong>IMDB rating:</strong>
<p><%= @movie.imdbrating %></p>

<% if not @movie.avg_rating.nil?%>
<strong> Marathoner rating:</strong>
<p><%= @movie.avg_rating %></p>
<% end %>

app/views/movies/index.html.erb
<script>
$(function() {
	$( "#accordion" ).accordion();
});
</script>

<div class="row">
	<h1>Movies</h1>
	<div id="accordion">
		<%= render @movies %>
	</div>
</div>

app/views/movies/movie_search.html.erb
<div class="row">
	<% if @movie["Response"] == "True" %>
	<div class="large-4 columns">
		<div class="poster">
		<a class="th" href="<%= @movie['Poster'] %>">
		<img src="<%= @movie['Poster'] %>" >
		</a>
		</div>
	</div>
	<div class="large-6 columns">
		<h1><%= @movie["Title"] %></h1>
		<p><%= @movie['Year'] %></p>
		<p><%= @movie["Plot"] %></p>
		<hr>
		<%= render 'movies/form'  %>
	</div>
	<div class="large-2 columns panel">
		<strong>Released:</strong>
		<p><%= @movie['Released'] %></p>

		<strong>Directors:</strong>
		<ul class="no-bullet">
		<% @directors.each do |d| %>
			<li><%= d %> </li>
		<% end %>
		</ul>

		<strong>Writers:</strong>
		<ul class="no-bullet">
		<% @writers.each do |w| %>
			<li><%= w %> </li>
		<% end %>
		</ul>

		<strong>Actors:</strong>
		<ul class="no-bullet">
		<% @actors.each do |i| %>
			<li><%= i %></li>
		<% end %>
		</ul>

		<strong>Genres:</strong>
		<ul class="no-bullet">
		<% @genres.each do |g| %>
			<li><%= g %> </li>
		<% end %>
		</ul>
		<strong>Runtime:</strong>
		<p><%= @movie["Runtime"] %></p>
		<strong>IMDB rating:</strong>
		<p><%= @movie["imdbRating"] %></p>

	</div>

	<% else %>
		<h2>No matching movie found, sorry.</h2>
	<% end %>

</div>

app/views/movies/show.html.erb
<script>
$(function() {
	$( "#accordion" ).accordion();
});
</script>

<div class="row">
	<div class="large-4 columns">
		<div class="poster">
		<a class="th" href="<%= @movie.poster %>">
		<img src="<%= @movie.poster %>" >
		</a>
		</div>
	</div>
	<div class="large-6 columns">
		<h1><%= @movie.title %></h1>
		<p><%= @movie.year %></p>
		<p><%= @movie.plot %></p>
		<% if logged_in? %>
		<hr>

		<% if @movie.reviewed_by current_user %>
			<%= link_to "Edit your review", edit_movie_review_path(@movie, @review), class:"button" %>
			<%= link_to "Remove your review", [@movie, @review], method: :delete, data: {confirm: "Delete review?"}, title: "Your review", class:"button alert"%>
		<% else %>
			<%= link_to "Review this movie", new_movie_review_path( @movie ), class:"button" %>
		<% end %>
		<% if @reviews.any? %>
			<div id="accordion">
				<%= render @reviews %>
			</div>
		<% else %>
			<h3>This movie has not been reviewed by anyone yet!</h3>
		<% end %>
	<% end %>
	</div>
	<div class="large-2 columns panel">
		<%= render 'stats' %>
	</div>

</div>