config/routes.rb
Moviemarathonhelper::Application.routes.draw do
  
  resources :movies do
      resources :reviews
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :reviews
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'
  match '/search_movie', to: 'movies#movie_search'
  match '/logout', to: 'sessions#destroy'
  match '/help', to: 'static_pages#help'
  

end

app/views/layouts/_nav.html.erb
<nav class="top-bar">
 <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><%= link_to "Movie Marathon Helper", root_path %></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

	<section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
     
    </ul>

    <!-- Right Nav Section -->
    <ul class="right">
   		<li class="divider"></li>
      <li><%= link_to "Home", root_path%></li>
      <li class="divider"></li>
      <li><%= link_to "Help", help_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Marathon Men", users_path %></li>
      <% if current_user %>
      <li class="divider"></li>
      <li><%= link_to "Movies", movies_path %></li>
      <% end %>
      <li class="divider"></li>
      <li class="has-form">
          <div class="row collapse">
            <div class="small-8 columns">
              <%= form_tag controller:"movies", action: "movie_search" do %>
                <%= text_field_tag :movie, nil, placeholder: 'Movie title or IMDB id' %>
            </div>
            <div class="small-4 columns">
                <%= submit_tag "Search movie", class: "alert button" %>
            </div>
          </div>
        <% end %>
      </li>
      <li class="divider show-for-small"></li>
      <% if current_user %>
      <li class="has-dropdown"><a href="#">Account</a>
        <ul class="dropdown">
          <li><%= link_to "Log out", logout_path %></li>
          <li><%= link_to "Edit account", edit_user_path(current_user) %></li>
        </ul>
      </li>
      <% else %>
      <li><%= link_to "Create an account", new_user_path %></li>
      <li><%= link_to "Log in", new_session_path%></li>
       <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title>Movie Marathon Helper</title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <% flash.each do |key,value| %>
      <div class="alert-box <%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>